# Generated by Django 5.2.7 on 2025-10-31 21:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effMobApp', '0003_make_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
