# Generated by Django 5.2.7 on 2025-10-31 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('effMobApp', '0004_users_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroles',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
