# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('effMobApp', '0005_userroles_last_updated_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='last_updated_by',
            new_name='created_by',
        ),
    ]
